### ISSUE TITLE
can I get a demo?

### ISSUE THREAD

**Issue by realchen** [gi097/json_parser#1]
hello,I did all like your document
but the code dosen't run 
no error but application is finished .

**Comment by gi097** [comment]
That's weird. Did you follow all steps? Could you show your code?

**Comment by realchen** [comment]
Thanks for answer!
I follow all steps,and .reflectable.dart is generated .
there is a question that the below words means creat a file or something else?
In order to make the mapping work, you need to create a new Dart object which has the same property names as your JSON. We are using the following example:

but 
void main() {
  initializeReflectable();
  runApp(new MaterialApp(
    home: new Login(),
    debugShowCheckedModeBanner: false,
    routes: <String, WidgetBuilder>{
      "main": (BuildContext context) => new MyApp(),
      //add more routes here
    },
  ));
}

void doLogin(BuildContext mcontext) {
    var url = "http://192.168.30.15:8080/mockjsdata/32/login";
    http.post(url, body: {
      "password": "111",
      "sign": "222",
      "timestamp": "blue",
      "username": "blue"
    }).then((response) {
      print("Response status: ${response.statusCode}");
      print("Response body: ${response.body}");
      print("==========**************************");
      parseJson(response.body);
      /*if (true) {
        jump(mcontext);
      }*/
    });
  }

  void parseJson(String json) {
    print("==========开始解析JSON");
    JsonParser parser = new JsonParser();
    LoginModel model = parser.parseJson<LoginModel>(json);
    print("==========" + model.toString());
  }


and the Class file
import 'package:json_parser/reflectable.dart';

@reflectable
class LoginModel {
  Data data;
  String msg;
  String result;

  LoginModel({this.data, this.msg, this.result});

  LoginModel.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    msg = json['msg'];
    result = json['result'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    data['msg'] = this.msg;
    data['result'] = this.result;
    return data;
  }
}

class Data {
  String oAAccount;
  String signTimeAM;
  String signTimePM;
  String company;
  String companyId;
  String department;
  String employeeNo;
  String leader;
  String permissions;
  String phoneNumber;
  String position;
  String realName;
  String userIcon;

  Data(
      {this.oAAccount,
      this.signTimeAM,
      this.signTimePM,
      this.company,
      this.companyId,
      this.department,
      this.employeeNo,
      this.leader,
      this.permissions,
      this.phoneNumber,
      this.position,
      this.realName,
      this.userIcon});

  Data.fromJson(Map<String, dynamic> json) {
    oAAccount = json['OAAccount'];
    signTimeAM = json['SignTimeAM'];
    signTimePM = json['SignTimePM'];
    company = json['company'];
    companyId = json['companyId'];
    department = json['department'];
    employeeNo = json['employeeNo'];
    leader = json['leader'];
    permissions = json['permissions'];
    phoneNumber = json['phoneNumber'];
    position = json['position'];
    realName = json['realName'];
    userIcon = json['userIcon'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['OAAccount'] = this.oAAccount;
    data['SignTimeAM'] = this.signTimeAM;
    data['SignTimePM'] = this.signTimePM;
    data['company'] = this.company;
    data['companyId'] = this.companyId;
    data['department'] = this.department;
    data['employeeNo'] = this.employeeNo;
    data['leader'] = this.leader;
    data['permissions'] = this.permissions;
    data['phoneNumber'] = this.phoneNumber;
    data['position'] = this.position;
    data['realName'] = this.realName;
    data['userIcon'] = this.userIcon;
    return data;
  }
}

**Comment by gi097** [comment]
You need to make a few changes:

- You did not initialize the attributes with a default value
- You can remove redundant code
- You did not add the annotation to all classes

Something like this will work:

```dart
@reflectable
class LoginModel {
    Data data = new Data();
    String msg = "";
    String result = "";

    @reflectable
    class Data {
        String oAAccount = "";
        String signTimeAM = "";
        String signTimePM = "";
        String company = "";
        String companyId = "";
        String department = "";
        String employeeNo = "";
        String leader = "";
        String permissions = "";
        String phoneNumber = "";
        String position = "";
        String realName = "";
        String userIcon = "";
    }
}
```

**Comment by gi097** [comment]
Did you run `flutter packages pub run build_runner build` after your changes?

**Comment by realchen** [comment]
` void parseJson(String json) {
    print("==========begin parse");
    JsonParser parser = new JsonParser();
    LoginModel model = parser.parseJson<LoginModel>(json);
    print("==========" + model.toString());
  }`

but the console print nothing after parse
I/flutter (21420): Response status: 200
I/flutter (21420): Response body: {
I/flutter (21420):     "data": {
I/flutter (21420):         "phoneNumber": "1234512121",
I/flutter (21420):         "permissions": "\u6d4b\u8bd5\u5185\u5bb990iz",
I/flutter (21420):         "department": "\u5f00\u53d1\u90e8",
I/flutter (21420):         "SignTimeAM": "08:00:00",
I/flutter (21420):         "SignTimePM": "13:00:00",
I/flutter (21420):         "leader": "\u674e\u56db",
I/flutter (21420):         "userIcon": "http://mta.zttit.com:8080/images/eschool/sales_wangjie.jpg",
I/flutter (21420):         "OAAccount": "admin",
I/flutter (21420):         "companyId": "12",
I/flutter (21420):         "realName": "\u5f20\u4e09",
I/flutter (21420):         "position": "\u7ba1\u7406",
I/flutter (21420):         "company": "\u4e2d\u5929\u79d1\u6280\u8f6f\u4ef6\u6280\u672f\u6709\u9650\u516c\u53f8",
I/flutter (21420):         "employeeNo": "18000"
I/flutter (21420):     },
I/flutter (21420):     "result": "1",
I/flutter (21420):     "msg": "success"
I/flutter (21420): }
I/flutter (21420): ==========**************************
I/flutter (21420): ==========begin parse

**Comment by gi097** [comment]
Instead of printing the `model.toString()`, could you try to print some of it's properties? Also try to use the debugger please.

**Comment by realchen** [comment]
yes,I already excuted the command in Terminal

**Comment by gi097** [comment]
So, do you have a stacktrace?

**Comment by gi097** [comment]
Also post your `json` input please.

**Comment by realchen** [comment]
I try it myself first

thanks！

**Comment by gi097** [comment]
No problem. Please let me know what the problem was if you find a solution.

**Comment by realchen** [comment]
hi,
I find that if the model class just a object 
that gonna be ok
just like your doucument whrite

but in 
https://github.com/gi097/json_parser/issues/1#issuecomment-418656401
the class format is incorrect

**Comment by gi097** [comment]
I see, sorry for that. So it works now?

**Comment by realchen** [comment]
no
does it not support the json format?
only support the format in demo?

**Comment by gi097** [comment]
Please post your raw json as a txt file here. I will take a look to it and try to solve your issue.

**Comment by realchen** [comment]
‘’’
{
    "data": {
        "age": 31845,
        "car": "测试内容6p83",
        "name": "测试内容fsc8"
    },
    "msg": "测试内容582o",
    "result": "测试内容d4j3"
}
‘’’

**Comment by realchen** [comment]
by the way 
can I just creat a model only contains 
{
        "age": 31845,
        "car": "aaa",
        "name": "bbb"
}
then how to get the data object and parse the json to Object or Object List

**Comment by gi097** [comment]
Please wait. I will fix the code today to support your json structure.

**Comment by realchen** [comment]
fine 
thanks a lot

**Comment by gi097** [comment]
Should be resolved in 7819a252e13a3d785b4e348dfd9381b224db9e5d. I have updated the package to version `0.1.6`. 

I tested it using the following json:
```json
{ "name":"Chen", "response": { "result": 5 } }
```
Which can be found here: https://github.com/gi097/json_parser/tree/develop/test


Thanks for making this issue!

**Comment by realchen** [comment]
that's ok.thanks 

but if the json structure contains both object and list like:
```
{
	"data": {
		"age": 30,
		"car": "BMW X1",
		"name": "chen"
	},
	"list": [{
			"money": "17000",
			"month": "2018/08"
		},
		{
			"money": "34000",
			"month": "2018/09"
		}
	],
	"msg": "success",
	"result": "1"
}
```

how to generate the class?
I try to write like this,but it doesn't work
```
@reflectable
class LoginModel {
  String result = "";
  String msg = "";
  Data data = new Data();
  List<Salary> _list = [];

  List<Salary> get list => _list;

  set list(List list) {
    _list = list.cast<Salary>();
  }
}

@reflectable
class Data {
  String name = "";
  int age = 0;
  String car = "";
}

@reflectable
class Salary {
  String month = "";
  String money = "";
}
```

**Comment by gi097** [comment]
Should work. Did you re-generate the class before trying?

**Comment by realchen** [comment]
may be the reason,now it run ok!

thanks for help me !
