### ISSUE TITLE
may be a bug

### ISSUE THREAD

**Issue by realchen** [gi097/json_parser#3]
hi
may be I find a problem
after you fix the bug ,I run all the code ok
but today when I try to run release mode,it occurs some mistake,
all the code are ok in debug mode
then,I write a demo and confirm the issue
here is some StackTrace,would you please see this?

type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Station' in type cast
E/flutter ( 3984): #0      _CastListBase.[] (dart:_internal/cast.dart:99)
E/flutter ( 3984): #1      _MyHomePageState.parseStationListJson (file:///E:/FlutterProjects/flutter_testjson/lib/main.dart:148)
E/flutter ( 3984): #2      _MyHomePageState.getStationList.<anonymous closure> (file:///E:/FlutterProjects/flutter_testjson/lib/main.dart:136)

the class is :
```
import 'package:json_parser/reflectable.dart';

@reflectable
class StationListModel {
  String result = "";
  String msg = "";
  List<Station> _list = [];

  List<Station> get data => _list;

  set data(List list) {
    _list = list.cast<Station>();
  }
}

@reflectable
class Station {
  bool isSelect = false;
  String address = "";
  String id = "";
  String name = "";
}
```
and the json input is ：
```
{
"msg": "success",
"result": "1",
"data": [
    {
        "isSelect": true,
        "address": "\u4e2d\u5929\u8def1\u53f7",
        "id": "1",
        "name": "\u7ad9\u70b91"
    },
    {
        "isSelect": false,
        "address": "\u4e2d\u5929\u8def2\u53f7",
        "id": "2",
        "name": "\u7ad9\u70b92"
    },
    {
        "isSelect": false,
        "address": "\u4e2d\u5929\u8def3\u53f7",
        "id": "3",
        "name": "\u7ad9\u70b93"
    },
    {
        "isSelect": false,
        "address": "\u4e2d\u5929\u8def4\u53f7",
        "id": "4",
        "name": "\u7ad9\u70b94"
    },
    {
        "isSelect": false,
        "address": "\u4e2d\u5929\u8def5\u53f7",
        "id": "5",
        "name": "\u7ad9\u70b95"
    }
]
}
```
all the code works ok in debug mode

**Comment by realchen** [comment]
any way to resolve this?

**Comment by gi097** [comment]
I will take a look later, currently I am very busy. Do you have turned on any kind of obfuscation? Make sure you build without obfuscation and test if it works. https://stackoverflow.com/questions/50542764/how-to-obfuscate-flutter-apps

**Comment by realchen** [comment]
> I will take a look later, currently I am very busy. Do you have turned on any kind of obfuscation? Make sure you build without obfuscation and test if it works. https://stackoverflow.com/questions/50542764/how-to-obfuscate-flutter-apps

ok,thanks
there is no obfuscation

**Comment by realchen** [comment]
can you confirm it's a bug?

I just use the command to generate a apk or run on a device:
```
flutter build apk --release

flutter run --release
```

**Comment by gi097** [comment]
It must be a bug since your code looks okay to me. It works in debug mode right?

**Comment by realchen** [comment]
> It must be a bug since your code looks okay to me. It works in debug mode right?

yes

**Comment by realchen** [comment]
excuse me 
is there any progress of the bug fix?

**Comment by gi097** [comment]
Please send me your full project by email, so I can test it properly.

**Comment by gi097** [comment]
No I did not receive anything. Maybe you can send it again to my email address?

**Comment by realchen** [comment]
> No I did not receive anything. Maybe you can send it again to my email address?

I just sent it again,have you recieved?

**Comment by gi097** [comment]
Yes I received it. I will try to take a look at it as soon as possible.

**Comment by realchen** [comment]
> Yes I received it. I will try to take a look at it as soon as possible.

thanks a lot

**Comment by gi097** [comment]
Hello, is this still a problem for you?
