### ISSUE TITLE
ignore property

### ISSUE THREAD

**Issue by sinanekiz** [gi097/json_parser#4]
Why we must write all property in our dart class ? ı want to ignore some property from json . is there any way?

**Comment by gi097** [comment]
I am not sure if this is a real requirement, I will take a look soon and notify you.

**Comment by gi097** [comment]
I fixed this in f4bbd52, use version `0.1.7` in your Flutter project. Please close this issue if the problem is solved for you.

**Comment by sinanekiz** [comment]
ok ı will try

**Comment by sinanekiz** [comment]
I am requesting a web api and   there are 100 property but I am only need 3 Property. this is required because ı dont want to write all property in my dart class,

**Comment by gi097** [comment]
I understand. It should have been fixed in the latest version. Did you try it?

**Comment by sinanekiz** [comment]
thank you , you are good :) I believe this plugin will be the best json parser from flutter but I'm sure I will open many issue next time :)
